module.exports = (base_data) => `{
  "name": "${base_data.name}",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build_dev": "node cli/build/build.dev.js",
    "build_test": "node cli/build/build.test.js",
    "watch": "node cli/build/build.location.js  --watch=true",
    "build": "node cli/build/build.js",
    "json_to_language_file": "node cli/translation/json_to_language_file.js",
    "language_file_to_json": "node cli/translation/language_file_to_json.js"
  },
  "devDependencies": {
    "autoprefixer": "^8.1.0",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-plugin-component": "^1.1.0",
    "babel-plugin-import": "^1.6.7",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "css-loader": "^0.28.10",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.11",
    "gulp": "^3.9.1",
    "html-webpack-plugin": "^3.0.6",
    "iview": "^2.14.3",
    "iview-loader": "^1.0.0",
    "jquery": "^3.3.1",
    "node-sass": "^4.7.2",
    "node-ssh": "^5.1.1",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^2.0.0",
    "postcss-loader": "^2.1.1",
    "sass-loader": "^6.0.7",
    "style-loader": "^0.20.3",
    "uglifyjs-webpack-plugin": "^1.2.3",
    "url-loader": "^1.0.1",
    "vue": "^2.5.15",
    "vue-loader": "^14.2.1",
    "vue-style-loader": "^4.0.2",
    "vue-template-compiler": "^2.5.15",
    "webpack": "^3.6.0",
    "webpack-merge": "^4.1.2",
    "yargs": "^11.0.0"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "libs-js": "^1.0.19",
    "vue-qriously": "^1.1.1",
    "vue-router": "^3.0.1",
    "vue-ueditor": "^0.1.3",
    "vuex": "^3.0.1",
    "vuex-router-sync": "^5.0.0",
    "xmlstring2json": "^0.1.9"
  },
  "author": "",
  "license": "ISC"
}
`;